package domain

import (
	"fmt"
	"time"
)

// StorageType identifies the Restic repository backend.
type StorageType string

const (
	StorageLocal StorageType = "local"
	StorageS3    StorageType = "s3"
	StorageSFTP  StorageType = "sftp"
	StorageREST  StorageType = "rest" // restic REST server
)

func (t StorageType) Valid() bool {
	switch t {
	case StorageLocal, StorageS3, StorageSFTP, StorageREST:
		return true
	}
	return false
}

// StorageConfig describes a Restic repository target.
//
// Credentials and ResticPassword are persisted encrypted (AES-256-GCM under
// the SDB master key) and only decrypted in memory when a Restic process is
// spawned. The Restic password is encrypted rather than hashed because
// Restic needs the actual value to open the repository.
type StorageConfig struct {
	ID          int64
	Name        string
	Type        StorageType
	Endpoint    string            // filesystem path (local) or URL (s3/sftp/rest)
	Credentials map[string]string // backend secrets, e.g. AWS_ACCESS_KEY_ID
	// ResticPassword protects the repository (Restic derives its AES-256
	// keys from it). Generated by SDB when the storage is created.
	ResticPassword string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (s *StorageConfig) Validate() error {
	if s.Name == "" {
		return fmt.Errorf("%w: storage name is required", ErrInvalidInput)
	}
	if !s.Type.Valid() {
		return fmt.Errorf("%w: unknown storage type %q", ErrInvalidInput, s.Type)
	}
	if s.Endpoint == "" {
		return fmt.Errorf("%w: storage endpoint is required", ErrInvalidInput)
	}
	if s.ResticPassword == "" {
		return fmt.Errorf("%w: restic repository password is required", ErrInvalidInput)
	}
	return nil
}

// Redacted returns a copy safe to expose over the API: secret values are
// blanked, only credential keys are kept so the UI can show what is set.
func (s *StorageConfig) Redacted() StorageConfig {
	out := *s
	out.ResticPassword = ""
	out.Credentials = make(map[string]string, len(s.Credentials))
	for k := range s.Credentials {
		out.Credentials[k] = ""
	}
	return out
}
